TrelloClient/Controllers/BoardsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TrelloClient.Models;
using TrelloNet;

namespace TrelloClient.Controllers
{
    public class BoardsController : Controller
    {
        // GET: Boards
        [HttpGet]
            public ViewResult Index()
        {
            List<SimpleBoardModel> simpleBoardModel = (List<SimpleBoardModel>)Session["simpleboardmodel"];
            return View(simpleBoardModel);
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult GetCards(string Id)
        {
            var simpleBoardModel = new SimpleBoardModel
            {
                Id = Id
            };
            Session["id"] = simpleBoardModel.Id;

            return RedirectToAction("Index","Cards");
        }
    }
}

TrelloClient/Views/Boards/Index.cshtml
@model IList<TrelloClient.Models.SimpleBoardModel>

@{
    ViewBag.Title = "Comment";
}
@Html.AntiForgeryToken()
@using (Html.BeginForm("getCards", "Boards", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post))
{
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Boards</th>
                <th>Pick a card to comment</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var board in Model)
            {
                <tr>
                    <td>@board.Name</td>
                    <td>
                        <div class="comment-form-submit">
                                @Html.ActionLink("See cards", "GetCards", "Boards", new { Id = board.Id }, new { })
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}